import type { CecExpression } from './ast';

export type CecTptpRole =
  | 'axiom'
  | 'conjecture'
  | 'hypothesis'
  | 'lemma'
  | 'theorem'
  | 'definition'
  | 'type'
  | 'negated_conjecture';

export interface CecTptpFormulaRecord {
  readonly formula: CecExpression;
  readonly role: CecTptpRole;
  readonly name: string;
  readonly tptp: string;
}

export const CEC_TPTP_UTILS_RUNTIME = {
  module: 'logic/CEC/provers/tptp_utils.py',
  runtime: 'browser-native-typescript',
  pythonRuntime: false,
  serverDelegation: false,
} as const;

export function cecFormulaToTptp(
  formula: CecExpression,
  role: CecTptpRole = 'conjecture',
  name = 'formula',
): string {
  return `fof(${sanitizeTptpIdentifier(name, 'formula')}, ${role}, ${translateCecFormulaToTptp(formula)}).`;
}

export function translateCecFormulaToTptp(formula: CecExpression): string {
  switch (formula.kind) {
    case 'atom':
      return sanitizeTptpIdentifier(formula.name, 'atom');
    case 'application':
      return translateApplication(formula);
    case 'unary':
      return translateUnary(formula.operator, formula.expression);
    case 'binary':
      return translateBinary(formula.operator, formula.left, formula.right);
    case 'quantified':
      return translateQuantified(formula.quantifier, formula.variable, formula.expression);
  }
}

export function createCecTptpProblem(
  conjecture: CecExpression,
  axioms: readonly CecExpression[] = [],
  options: {
    readonly problemName?: string;
    readonly axiomNamePrefix?: string;
    readonly conjectureName?: string;
  } = {},
): string {
  const axiomPrefix = options.axiomNamePrefix ?? 'ax';
  const lines = [
    `% Problem: ${options.problemName ?? 'cec_problem'}`,
    '% Generated by CEC TPTP utilities',
    '',
    ...axioms.map((axiom, index) => cecFormulaToTptp(axiom, 'axiom', `${axiomPrefix}${index + 1}`)),
  ];
  if (axioms.length > 0) lines.push('');
  lines.push(cecFormulaToTptp(conjecture, 'conjecture', options.conjectureName ?? 'goal'));
  return lines.join('\n');
}

export function createCecTptpFormula(
  formula: CecExpression,
  role: CecTptpRole = 'conjecture',
  name = 'f1',
): CecTptpFormulaRecord {
  return {
    formula,
    role,
    name: sanitizeTptpIdentifier(name, 'f1'),
    tptp: cecFormulaToTptp(formula, role, name),
  };
}

export class CecTptpConverter {
  convert(formula: CecExpression, role: CecTptpRole = 'conjecture', name = 'f1'): string {
    return cecFormulaToTptp(formula, role, name);
  }

  createProblem(
    conjecture: CecExpression,
    axioms: readonly CecExpression[] = [],
    problemName = 'problem',
  ): string {
    return createCecTptpProblem(conjecture, axioms, { problemName });
  }

  convertFormula(formula: CecExpression): CecTptpFormulaRecord {
    return createCecTptpFormula(formula);
  }
}

function translateApplication(formula: Extract<CecExpression, { kind: 'application' }>): string {
  const name = sanitizeTptpIdentifier(formula.name, 'predicate');
  if (formula.args.length === 0) return name;
  return `${name}(${formula.args.map(translateCecFormulaToTptp).join(', ')})`;
}

function translateUnary(operator: string, expression: CecExpression): string {
  const inner = translateCecFormulaToTptp(expression);
  if (operator === 'not') return `~(${inner})`;
  const predicate =
    operator === 'O'
      ? 'obligated'
      : operator === 'P'
        ? 'permitted'
        : operator === 'F'
          ? 'forbidden'
          : operator;
  return `${sanitizeTptpIdentifier(predicate, 'unary')}(${inner})`;
}

function translateBinary(operator: string, left: CecExpression, right: CecExpression): string {
  const lhs = translateCecFormulaToTptp(left);
  const rhs = translateCecFormulaToTptp(right);
  if (operator === 'and') return `(${lhs} & ${rhs})`;
  if (operator === 'or') return `(${lhs} | ${rhs})`;
  if (operator === 'implies') return `(${lhs} => ${rhs})`;
  if (operator === 'iff') return `(${lhs} <=> ${rhs})`;
  if (operator === 'xor') return `(~(${lhs} <=> ${rhs}))`;
  return `${sanitizeTptpIdentifier(operator, 'binary')}(${lhs}, ${rhs})`;
}

function translateQuantified(
  quantifier: string,
  variable: string,
  expression: CecExpression,
): string {
  const marker = quantifier === 'forall' ? '!' : '?';
  return `(${marker} [${sanitizeTptpVariable(variable)}] : ${translateCecFormulaToTptp(expression)})`;
}

function sanitizeTptpIdentifier(value: string, fallback: string): string {
  const normalized = value
    .trim()
    .replace(/[^A-Za-z0-9_]/g, '_')
    .replace(/_+/g, '_');
  const candidate = normalized.length > 0 ? normalized : fallback;
  const lower = /^[A-Z]/.test(candidate) ? candidate.toLowerCase() : candidate;
  return /^[a-z_$]/.test(lower) ? lower : `${fallback}_${lower}`;
}

function sanitizeTptpVariable(value: string): string {
  const normalized = value
    .trim()
    .replace(/[^A-Za-z0-9_]/g, '_')
    .replace(/_+/g, '_');
  const candidate = normalized.length > 0 ? normalized : 'X';
  const upper = candidate[0].toUpperCase() + candidate.slice(1);
  return /^[A-Z]/.test(upper) ? upper : `X_${upper}`;
}
